### ISSUE TITLE
npm install printer fails

### ISSUE THREAD

**Issue by TheBeachLab** [fabfoundation/mods#2]
Even with dependencies installed (libcups, node-gyp, rebuild). Error log below
```
make: *** [node_printer.target.mk:106: Release/obj.target/node_printer/src/node_printer_posix.o] Error 1
make: Leaving directory '/home/unix/Repositories/Fab/mods/js/node_modules/printer/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.0-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/unix/Repositories/Fab/mods/js/node_modules/printer
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/unix/Repositories/Fab/mods/js/package.json'
npm WARN js No description
npm WARN js No repository field.
npm WARN js No README data
npm WARN js No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! printer@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the printer@0.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/unix/.npm/_logs/2019-09-23T17_42_07_355Z-debug.log
```

In the past I could install it with no problems

**Comment by TheBeachLab** [comment]
No longer fails now with the current version of npm 6.13.6 and printer 0.4.0
